#ifndef KYRAGAMEFRAMEWORK_GLEXTENSIONLOADER_DLL_HPP
#define KYRAGAMEFRAMEWORK_GLEXTENSIONLOADER_DLL_HPP

#ifdef KYRA_GLEXTENSIONLOADER_EXPORTS
  #define KYRA_GLEXTENSIONLOADER_API __declspec(dllexport)
#else
  #define KYRA_GLEXTENSIONLOADER_API __declspec(dllimport)
#endif

#endif