#ifndef KYRAGAMEFRAMEWORK_GLEXTENSIONLOADER_GLEXTENSIONLOADER_HPP
#define KYRAGAMEFRAMEWORK_GLEXTENSIONLOADER_GLEXTENSIONLOADER_HPP

#include <KyraGameFramework/GLExtensionLoader/DLL.hpp>

#include <GL/gl.h>
#include <GL/glext.h>
#include <GL/wglext.h>

// BUFFER FUNCTIONS
KYRA_GLEXTENSIONLOADER_API extern PFNGLGENBUFFERSPROC glGenBuffers;
KYRA_GLEXTENSIONLOADER_API extern PFNGLBINDBUFFERPROC glBindBuffer;
KYRA_GLEXTENSIONLOADER_API extern PFNGLBUFFERDATAPROC	glBufferData;
KYRA_GLEXTENSIONLOADER_API extern PFNGLDELETEBUFFERSPROC glDeleteBuffers;

//SHADER FUNCTIONS
KYRA_GLEXTENSIONLOADER_API extern PFNGLCREATESHADERPROC glCreateShader;
KYRA_GLEXTENSIONLOADER_API extern PFNGLCOMPILESHADERPROC glCompileShader;
KYRA_GLEXTENSIONLOADER_API extern PFNGLSHADERSOURCEPROC	glShaderSource;
KYRA_GLEXTENSIONLOADER_API extern PFNGLGETSHADERIVPROC glGetShaderiv;
KYRA_GLEXTENSIONLOADER_API extern PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
KYRA_GLEXTENSIONLOADER_API extern PFNGLDELETESHADERPROC glDeleteShader;

//PROGRAM FUNCTIONS
KYRA_GLEXTENSIONLOADER_API extern PFNGLCREATEPROGRAMPROC glCreateProgram;
KYRA_GLEXTENSIONLOADER_API extern PFNGLATTACHSHADERPROC glAttachShader;
KYRA_GLEXTENSIONLOADER_API extern PFNGLLINKPROGRAMPROC glLinkProgram;
KYRA_GLEXTENSIONLOADER_API extern PFNGLGETPROGRAMIVPROC glGetProgramiv;
KYRA_GLEXTENSIONLOADER_API extern PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
KYRA_GLEXTENSIONLOADER_API extern PFNGLUSEPROGRAMPROC glUseProgram;
KYRA_GLEXTENSIONLOADER_API extern PFNGLDELETEPROGRAMPROC glDeleteProgram;

//VERTEXLAYOUT FUNCTIONS
KYRA_GLEXTENSIONLOADER_API extern PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
KYRA_GLEXTENSIONLOADER_API extern PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
				

namespace kyra {
		
	class KYRA_GLEXTENSIONLOADER_API GLExtensionLoader {

		public:
		~GLExtensionLoader() = delete;
		
		static bool init();
		
	};
}



#endif