#ifndef KYRAGAMEFRAMEWORK_GLEXTENSIONLOADER_GLEXTENSIONLOADER_HPP
#define KYRAGAMEFRAMEWORK_GLEXTENSIONLOADER_GLEXTENSIONLOADER_HPP

#include <KyraGameFramework/GLExtensionLoader/DLL.hpp>

#include <GL/gl.h>
#include <GL/glext.h>
#include <GL/wglext.h>

// BUFFER FUNCTIONS
KYRA_GLEXTENSIONLOADER_API extern PFNGLGENBUFFERSPROC glGenBuffers;
KYRA_GLEXTENSIONLOADER_API extern PFNGLBINDBUFFERPROC glBindBuffer;
KYRA_GLEXTENSIONLOADER_API extern PFNGLBUFFERDATAPROC	glBufferData;
KYRA_GLEXTENSIONLOADER_API extern PFNGLDELETEBUFFERSPROC glDeleteBuffers;
KYRA_GLEXTENSIONLOADER_API extern PFNGLBUFFERSUBDATAPROC glBufferSubData;

//VERTEXARRAY FUNCTIONS
KYRA_GLEXTENSIONLOADER_API extern PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
KYRA_GLEXTENSIONLOADER_API extern PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
KYRA_GLEXTENSIONLOADER_API extern PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;

//SHADER FUNCTIONS
KYRA_GLEXTENSIONLOADER_API extern PFNGLCREATESHADERPROC glCreateShader;
KYRA_GLEXTENSIONLOADER_API extern PFNGLCOMPILESHADERPROC glCompileShader;
KYRA_GLEXTENSIONLOADER_API extern PFNGLSHADERSOURCEPROC	glShaderSource;
KYRA_GLEXTENSIONLOADER_API extern PFNGLGETSHADERIVPROC glGetShaderiv;
KYRA_GLEXTENSIONLOADER_API extern PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
KYRA_GLEXTENSIONLOADER_API extern PFNGLDELETESHADERPROC glDeleteShader;

//PROGRAM FUNCTIONS
KYRA_GLEXTENSIONLOADER_API extern PFNGLCREATEPROGRAMPROC glCreateProgram;
KYRA_GLEXTENSIONLOADER_API extern PFNGLATTACHSHADERPROC glAttachShader;
KYRA_GLEXTENSIONLOADER_API extern PFNGLLINKPROGRAMPROC glLinkProgram;
KYRA_GLEXTENSIONLOADER_API extern PFNGLGETPROGRAMIVPROC glGetProgramiv;
KYRA_GLEXTENSIONLOADER_API extern PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
KYRA_GLEXTENSIONLOADER_API extern PFNGLUSEPROGRAMPROC glUseProgram;
KYRA_GLEXTENSIONLOADER_API extern PFNGLDELETEPROGRAMPROC glDeleteProgram;
KYRA_GLEXTENSIONLOADER_API extern PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
KYRA_GLEXTENSIONLOADER_API extern PFNGLUNIFORM1IPROC glUniform1i;
KYRA_GLEXTENSIONLOADER_API extern PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
KYRA_GLEXTENSIONLOADER_API extern PFNGLUNIFORM3FVPROC glUniform3fv;

//VERTEXLAYOUT FUNCTIONS
KYRA_GLEXTENSIONLOADER_API extern PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
KYRA_GLEXTENSIONLOADER_API extern PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;

//TEXTURE FUNCTIONS
KYRA_GLEXTENSIONLOADER_API extern PFNGLGENERATEMIPMAPPROC glGenerateMipmap;
KYRA_GLEXTENSIONLOADER_API extern PFNGLACTIVETEXTUREPROC glActiveTexture;

//WGL EXTENSIONS
KYRA_GLEXTENSIONLOADER_API extern  PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB;

#include <iostream>
#define GL_CHECK(x) x; {GLenum err = glGetError(); if(err != GL_NO_ERROR) {std::cout <<"[ERROR] " << __FILE__ << " " << __LINE__ << " " << __PRETTY_FUNCTION__ << " Error in OpenGL-Function: " << #x << " ( " << err << " )" << std::endl;}}

namespace kyra {
		
	class KYRA_GLEXTENSIONLOADER_API GLExtensionLoader {

		public:
		~GLExtensionLoader() = delete;
		
		static bool init();
		
	};
}



#endif